// Originally generated by the template in CodeDAO
package kotlinadventofcode.`2015`

import kotlinadventofcode.Day
import java.math.BigInteger
import java.security.MessageDigest

fun md5(input:String): String {
    val md = MessageDigest.getInstance("MD5")
    return BigInteger(1, md.digest(input.toByteArray())).toString(16).padStart(32, '0')
}

class `2015-04` : Day {

    /**
     * After verifying your solution on the AoC site, run `./ka continue` to add a test for it.
     */
    override fun runPart1(input: String): String {
        var decimal: Int = 0
        do {
            decimal++
            val md5: String = md5(input + decimal.toString())
        } while (md5.subSequence(0, 5) != "00000")

        return decimal.toString()
    }

    /**
     * After verifying your solution on the AoC site, run `./ka continue` to add a test for it.
     */
    override fun runPart2(input: String): String {
        throw Exception("2015 day 04 part 2 isn't yet implemented.")
    }

    override val defaultInput = """ckczppom"""
}