/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotlinadventofcode

import kotlinadventofcode.UI.runWithKotterUI
import picocli.CommandLine
import picocli.CommandLine.Command
import picocli.CommandLine.Option
import picocli.CommandLine.Parameters

import java.util.concurrent.Callable
import kotlin.system.exitProcess

@Command(
    name = "ka",
    description = ["Runs Kotlin Advent of Code solutions."],
    subcommands = [ Continue::class ]
)
class App : Callable<Int> {

    @Parameters(
        index = "0",
        arity = "0..1",
        description = ["The day to run. Defaults to the last defined: \${DEFAULT-VALUE}. All: \${COMPLETION-CANDIDATES}"]
    )
    var problem: Problem = Problem.values().maxOrNull() ?: throw Exception("No instances defined in Problem enum.")

    @Option(names = ["--help", "-h"], usageHelp = true, hidden = true)
    var help = false

    override fun call(): Int {
        runWithKotterUI(problem) { ui ->
            val result = problem.run(ui)
            println(result)
            ui.setResult(result)
        }

        return 0
    }
}

fun main(args: Array<String>): Unit = exitProcess(CommandLine(App()).execute(*args))