// Originally generated by the template in CodeDAO
package kotlinadventofcode.`2023`

import kotlin.test.Test
import kotlin.test.assertEquals

class `2023-03-Test` {

    private infix fun String.when1runsWith(input: String) {
        assertEquals(this, `2023-03`().runPartOneNoUI(input))
    }

    private infix fun String.when2runsWith(input: String) {
        assertEquals(this, `2023-03`().runPartTwoNoUI(input))
    }

    @Test
    fun testExamplePart1() {
        assertEquals("4361", `2023-03`().runPartOneNoUI("""467..114..
...*......
..35..633.
......#...
617*......
.....+.58.
..592.....
......755.
...${'$'}.*....
.664.598.."""))
    }

    @Test fun testDefaultPart1() {
        assertEquals("540131", `2023-03`().runPartOneNoUI())
    }

    @Test fun testDefaultPart2() {
        assertEquals("86879020", `2023-03`().runPartTwoNoUI())
    }

}
