// Originally generated by the template in CodeDAO
package kotlinadventofcode.`2023`

import kotlinadventofcode.UI.NoOpUI
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class `2023-20-Test` {

    val example1 = """broadcaster -> a, b, c
%a -> b
%b -> c
%c -> inv
&inv -> a"""

    @Test fun example1time() {
        val day = `2023-20`()
        with (NoOpUI) {
            val result = day.runPartOne(example1, 1)
            assertEquals("32", result)
        }
    }

    @Test fun example2times() {
        val day = `2023-20`()
        with (NoOpUI) {
            val result = day.runPartOne(example1, 2)
            assertEquals("128", result)
        }
    }

    @Test fun example1000times() {
        val day = `2023-20`()
        with (NoOpUI) {
            val result = day.runPartOne(example1, 1_000)
            assertEquals("32000000", result)
        }
    }

    @Test fun testDefaultPart1() {
        assertEquals("739960225", `2023-20`().runPartOneNoUI())
    }

    @Test fun testDefaultPart2() {
        assertEquals("231897990075517", `2023-20`().runPartTwoNoUI())
    }
}
