// Originally generated by the template in CodeDAO
package kotlinadventofcode.`2023`

import kotlinadventofcode.`2023`.`2023-22`.Companion.Brick
import kotlinadventofcode.`2023`.`2023-22`.Companion.gravitized
import kotlinadventofcode.`2023`.`2023-22`.Companion.toBricks
import kotlinadventofcode.`2023`.`2023-22`.Companion.Coord
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class `2023-22-Test` {

    val example = """1,0,1~1,2,1
0,0,2~2,0,2
0,2,3~2,2,3
0,0,4~0,2,4
2,0,5~2,2,5
0,1,6~2,1,6
1,1,8~1,1,9"""

    @Test fun exampleGravity() {
        val bricks = example.toBricks()
        val expected = listOf(
            Brick(Coord(1,0,1), Coord(1,2,1)), // A
            Brick(Coord(0,0,2), Coord(2,0,2)), // B
            Brick(Coord(0,2,2), Coord(2,2,2)), // C
            Brick(Coord(0,0,3), Coord(0,2,3)), // D
            Brick(Coord(2,0,3), Coord(2,2,3)), // E
            Brick(Coord(0,1,4), Coord(2,1,4)), // F
            Brick(Coord(1,1,5), Coord(1,1,6))  // G
        ).toSet()

        assertEquals(expected, bricks.gravitized().first)
    }

    @Test fun testExample1() {
        assertEquals("5", `2023-22`().runPartOneNoUI(example))
    }

    @Test fun testDefaultPart1() {
        assertEquals("457", `2023-22`().runPartOneNoUI())
    }

    @Test fun testExamplePart2() {
        assertEquals("7", `2023-22`().runPartTwoNoUI(example))
    }

    @Test fun testDefaultPart2() {
        assertEquals("79122", `2023-22`().runPartTwoNoUI())
    }

}
