// Originally generated by the template in CodeDAO
package kotlinadventofcode.`2023`

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlinadventofcode.`2023`.`2023-11`.Companion.toUniverse
import java.math.BigInteger

class `2023-11-Test` {

    private infix fun String.when1runsWith(input: String) {
        assertEquals(this, `2023-11`().runPartOneNoUI(input))
    }

    private infix fun String.when2runsWith(input: String) {
        assertEquals(this, `2023-11`().runPartTwoNoUI(input))
    }

    @Test fun testGetGalaxies() {
        val universe = `2023-11`().defaultInput.toUniverse()
        val galaxies = universe.getGalaxies()
        assertEquals(430, galaxies.size)
    }

    @Test fun testDefaultPart1() {
        assertEquals("9418609", `2023-11`().runPartOneNoUI())
    }

    val exampleInput ="""...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#....."""

    @Test fun testExamplePart10() {
        val universe = exampleInput.toUniverse()
        val expandedUniverse = universe.expandBy(10)
        assertEquals("1030", expandedUniverse.galaxyDistances.reduce(BigInteger::add).toString())
    }

    @Test fun testExample2() {
        val universe = exampleInput.toUniverse()
        val expandedUniverse = universe.expandBy(2)
        assertEquals("374", expandedUniverse.galaxyDistances.reduce(BigInteger::add).toString())
    }

    @Test fun testDefaultPart2() {
        assertEquals("593821230983", `2023-11`().runPartTwoNoUI())
    }

}
