// Originally generated by the template in CodeDAO
package kotlinadventofcode.`2023`

import kotlinadventofcode.`2023`.`2023-21`.Companion.toMap
import kotlinadventofcode.UI.NoOpUI
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class `2023-21-Test` {

    @Test fun testDefaultPart1() {
        assertEquals("3770", `2023-21`().runPartOneNoUI())
    }

    val exampleInput = """...........
.....###.#.
.###.##..#.
..#.#...#..
....#.#....
.##..S####.
.##..#...#.
.......##..
.##.#.####.
.##..##.##.
..........."""

    @Test fun testExamplePart2Intermediate() {
        with (NoOpUI) {
            assertEquals("167004", exampleInput.toMap().getNumPositionsAfterSteps(500).toString())
        }
    }

    @Test fun testDefaultPart2() {
        assertEquals("628206330073385", `2023-21`().runPartTwoNoUI())
    }

}
