// Originally generated by the template in CodeDAO
package kotlinadventofcode.`2023`

import kotlinadventofcode.`2023`.`2023-12`.Companion.toRows
import kotlin.test.Test
import kotlin.test.assertEquals

class `2023-12-Test` {

    private infix fun String.when1runsWith(input: String) {
        assertEquals(this, `2023-12`().runPart1(input))
    }

    private infix fun String.when2runsWith(input: String) {
        assertEquals(this, `2023-12`().runPart2(input))
    }

    val exampleInput = """???.### 1,1,3
.??..??...?##. 1,1,3
?#?#?#?#?#?#?#? 1,3,1,6
????.#...#... 4,1,1
????.######..#####. 1,6,5
?###???????? 3,2,1"""

    @Test fun testPart1Example() {
        val algo2 = exampleInput.toRows().map { it.numValidArrangements }
        assertEquals("21", `2023-12`().runPart1(exampleInput))
    }

    @Test fun testPart2Example() {
        assertEquals("525152", `2023-12`().runPart2(exampleInput))
    }

    @Test fun testDefaultPart1() {
        assertEquals("6852", `2023-12`().runPart1())
    }

    @Test fun testDefaultPart2() {
        assertEquals("8475948826693", `2023-12`().runPart2())
    }

}
