// Originally generated by the template in CodeDAO
package kotlinadventofcode.`2023`

import kotlin.test.Test
import kotlin.test.assertEquals

class `2023-18-Test` {

    @Test fun testDefaultPart1() {
        assertEquals("50465", `2023-18`().runPartOneNoUI())
    }

    @Test fun testDefaultPart2() {
        assertEquals("82712746433310", `2023-18`().runPartTwoNoUI())
    }

}
