// Originally generated by the template in CodeDAO
package kotlinadventofcode.`2023`

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class `2023-02-Test` {

    private infix fun String.when1runsWith(input: String) {
        assertEquals(this, `2023-02`().runPart1(input))
    }

    private infix fun String.when2runsWith(input: String) {
        assertEquals(this, `2023-02`().runPart2(input))
    }

    @Test fun testDefaultPart1() {
        assertEquals("2237", `2023-02`().runPart1())
    }

    @Test fun testDefaultPart2() {
        assertEquals("66681", `2023-02`().runPart2())
    }

}
