// Originally generated by the template in CodeDAO
package kotlinadventofcode.`2023`

import kotlinadventofcode.`2023`.`2023-23`.Companion.toGrid
import kotlinadventofcode.`2023`.`2023-23`.Companion.Grid.Coord
import kotlinadventofcode.UI.forEach
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class `2023-23-Test` {

    val example = """#.#####################
#.......#########...###
#######.#########.#.###
###.....#.>.>.###.#.###
###v#####.#v#.###.#.###
###.>...#.#.#.....#...#
###v###.#.#.#########.#
###...#.#.#.......#...#
#####.#.#.#######.#.###
#.....#.#.#.......#...#
#.#####.#.#.#########v#
#.#...#...#...###...>.#
#.#.#v#######v###.###v#
#...#.>.#...>.>.#.###.#
#####v#.#.###v#.#.###.#
#.....#...#...#.#.#...#
#.#########.###.#.#.###
#...###...#...#...#.###
###.###.#.###v#####v###
#...#...#.#.>.>.#.>.###
#.###.###.#.###.#.#v###
#.....###...###...#...#
#####################.#"""

    @Test fun testDefaultPart1() {
        assertEquals("2366", `2023-23`().runPartOneNoUI())
    }

    @Test fun testExamplePart1() {
        assertEquals("94", `2023-23`().runPartOneNoUI(example))
    }

    @Test fun testExamplePart2() {
        assertEquals("154", `2023-23`().runPartTwoNoUI(example))
    }


    @Test fun testDefaultPart2() {
        assertEquals("6682", `2023-23`().runPartTwoNoUI())
    }

}
