// Originally generated by the template in CodeDAO
package kotlinadventofcode.`2023`

import kotlin.test.Test
import kotlin.test.assertEquals

class `2023-06-Test` {

    private infix fun String.when1runsWith(input: String) {
        assertEquals(this, `2023-06`().runPartOneNoUI(input))
    }

    private infix fun String.when2runsWith(input: String) {
        assertEquals(this, `2023-06`().runPartTwoNoUI(input))
    }

    @Test fun testDefaultPart1() {
        assertEquals("345015", `2023-06`().runPartOneNoUI())
    }

    @Test fun testDefaultPart2() {
        assertEquals("42588603", `2023-06`().runPartTwoNoUI())
    }

}
