// Originally generated by the template in CodeDAO
package kotlinadventofcode.`2023`

import kotlinadventofcode.`2023`.`2023-14`.Companion.toPlatform
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class `2023-14-Test` {

    private infix fun String.when1runsWith(input: String) {
        assertEquals(this, `2023-14`().runPart1(input))
    }

    private infix fun String.when2runsWith(input: String) {
        assertEquals(this, `2023-14`().runPart2(input))
    }

    val exampleInput = """O....#....
O.OO#....#
.....##...
OO.#O....O
.O.....O#.
O.#..O.#.#
..O..#O..O
.......O..
#....###..
#OO..#...."""

    val exampleTiltedNorth = """OOOO.#.O..
OO..#....#
OO..O##..O
O..#.OO...
........#.
..#....#.#
..O..#.O.O
..O.......
#....###..
#....#...."""

    @Test fun testExamplePart1() {
        assertEquals("136", `2023-14`().runPart1(exampleInput))
    }

    @Test fun testExamplePart2() {
        assertEquals("64", `2023-14`().runPart2(exampleInput))
    }

    @Test fun exampleTiltedNorth() {
        assertEquals(exampleTiltedNorth, exampleInput.toPlatform().tiltedNorth.toString())
    }

    @Test fun testDefaultPart1() {
        assertEquals("105208", `2023-14`().runPart1())
    }

    @Test fun testDefaultPart2() {
        assertEquals("102943", `2023-14`().runPart2())
    }

}
