// Originally generated by the template in CodeDAO
package kotlinadventofcode.`2022`

import kotlin.test.Test
import kotlin.test.assertEquals

class `2022-15-Test` {

    private infix fun String.when1runsWith(input: String) {
        assertEquals(this, `2022-15`().runPartOneNoUI(input))
    }

    private infix fun String.when2runsWith(input: String) {
        assertEquals(this, `2022-15`().runPartTwoNoUI(input))
    }

    @Test fun testDefaultPart1() {
        assertEquals("4883971", `2022-15`().runPartOneNoUI())
    }

    @Test fun testDefaultPart2() {
        assertEquals("12691026767556", `2022-15`().runPartTwoNoUI())
    }

}
