// Originally generated by the template in CodeDAO
package kotlinadventofcode.`2022`

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class `2022-19-Test` {

    private infix fun String.when1runsWith(input: String) {
        assertEquals(this, `2022-19`().runPart1(input))
    }

    private infix fun String.when2runsWith(input: String) {
        assertEquals(this, `2022-19`().runPart2(input))
    }

    // DO NOT DELETE. Part 1 placeholder. To populate, verify solution on AoC then `./ka continue`

    // DO NOT DELETE. Part 2 placeholder. To populate, verify solution on AoC then `./ka continue`


    @Test fun testExample1() {
        "9" when1runsWith """Blueprint 1: Each ore robot costs 4 ore. Each clay robot costs 2 ore. Each obsidian robot costs 3 ore and 14 clay. Each geode robot costs 2 ore and 7 obsidian."""
    }

}