// Originally generated by the template in CodeDAO
package kotlinadventofcode.`2022`

import kotlin.test.Test
import kotlin.test.assertEquals

class `2022-03-Test` {

    private infix fun String.when1runsWith(input: String) {
        assertEquals(this, `2022-03`().runPartOneNoUI(input))
    }

    private infix fun String.when2runsWith(input: String) {
        assertEquals(this, `2022-03`().runPartTwoNoUI(input))
    }

    @Test fun testDefaultPart1() {
        assertEquals("7850", `2022-03`().runPartOneNoUI())
    }

    @Test fun testDefaultPart2() {
        assertEquals("2581", `2022-03`().runPartTwoNoUI())
    }

}
