// Originally generated by the template in CodeDAO
package kotlinadventofcode.`2022`

import kotlin.test.Test
import kotlin.test.assertEquals

class `2022-02-Test` {

    private infix fun String.when1runsWith(input: String) {
        assertEquals(this, `2022-02`().runPartOneNoUI(input))
    }

    private infix fun String.when2runsWith(input: String) {
        assertEquals(this, `2022-02`().runPartTwoNoUI(input))
    }

    @Test fun testDefaultPart1() {
        assertEquals("11767", `2022-02`().runPartOneNoUI())
    }

    @Test fun testDefaultPart2() {
        assertEquals("13886", `2022-02`().runPartTwoNoUI())
    }

}
