// Originally generated by the template in CodeDAO
package kotlinadventofcode.`2022`

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class `2022-11-Test` {

    private infix fun String.when1runsWith(input: String) {
        assertEquals(this, `2022-11`().runPart1(input))
    }

    private infix fun String.when2runsWith(input: String) {
        assertEquals(this, `2022-11`().runPart2(input))
    }

    @Test fun testDefaultPart1() {
        assertEquals("110888", `2022-11`().runPart1())
    }

    @Test fun testDefaultPart2() {
        assertEquals("25590400731", `2022-11`().runPart2())
    }

}
