// Originally generated by the template in CodeDAO
package kotlinadventofcode.`2022`

import kotlin.test.Test
import kotlin.test.assertEquals

class `2022-09-Test` {

    private infix fun String.when1runsWith(input: String) {
        assertEquals(this, `2022-09`().runPartOneNoUI(input))
    }

    private infix fun String.when2runsWith(input: String) {
        assertEquals(this, `2022-09`().runPartTwoNoUI(input))
    }

    @Test fun testDefaultPart1() {
        assertEquals("5513", `2022-09`().runPartOneNoUI())
    }

    @Test fun testDefaultPart2() {
        assertEquals("2427", `2022-09`().runPartTwoNoUI())
    }


    @Test fun testExample() {
        "13" when1runsWith """R 4
U 4
L 3
D 1
R 4
D 1
L 5
R 2"""
    }
}
