// Originally generated by the template in CodeDAO
package kotlinadventofcode.`2022`

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class `2022-08-Test` {

    private infix fun String.when1runsWith(input: String) {
        assertEquals(this, `2022-08`().runPart1(input))
    }

    private infix fun String.when2runsWith(input: String) {
        assertEquals(this, `2022-08`().runPart2(input))
    }

    @Test fun testDefaultPart1() {
        assertEquals("1698", `2022-08`().runPart1())
    }

    @Test fun testDefaultPart2() {
        assertEquals("672280", `2022-08`().runPart2())
    }


    @Test fun testSmallPart2() {
        "8" when2runsWith
            """12711
              |45611
              |78921
              |28731""".trimMargin()
    }

    @Test fun testMedPart2() {
        "8" when2runsWith
            """12711
              |45611
              |87921
              |28731""".trimMargin()
    }

    @Test fun testMed2Part2() {
        "8" when2runsWith
            """12911
              |45911
              |87421
              |87921
              |28731""".trimMargin()
    }

    @Test fun testMed3Part2() {
        "8" when2runsWith
            """12911
              |45811
              |87421
              |87821
              |28731""".trimMargin()
    }
}
