// Originally generated by the template in CodeDAO
package kotlinadventofcode.`2022`

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class `2022-01-Test` {

    private infix fun String.when1runsWith(input: String) {
        assertEquals(this, `2022-01`().runPart1(input))
    }

    private infix fun String.when2runsWith(input: String) {
        assertEquals(this, `2022-01`().runPart2(input))
    }

    @Test fun testDefaultPart1() {
        assertEquals("70720", `2022-01`().runPart1())
    }

    // DO NOT DELETE. Part 2 placeholder. To populate, verify solution on AoC then `./ka continue`

}
