// Originally generated by the template in CodeDAO
package kotlinadventofcode.`2022`

import com.github.h0tk3y.betterParse.combinators.*
import com.github.h0tk3y.betterParse.grammar.*
import com.github.h0tk3y.betterParse.lexer.*
import kotlinadventofcode.Day

class `2022-05` : Day {

    data class Move(val num: Int, val fromStack: Int, val toStack: Int)

    class Stack {
        private var stack: ArrayDeque<Char> = ArrayDeque()

        constructor(containersTopToBottom: List<Char>) {
            containersTopToBottom.forEach { stack.addLast(it) }
        }

        fun push(container: Char) {
            stack.addFirst(container)
        }

        fun pop(): Char {
            return stack.removeFirst()
        }
    }

    private fun parse(input: String): List<Move> {
        val grammar = object : Grammar<List<Move>>() {

            /*
             * Tokens must be declared by themselves—i.e. they must be a declared property in this object.
             * Declaration order will be used in the case that multiple tokens match.
             */
            val moveLit by literalToken("move ")
            val fromLit by literalToken(" from ")
            val toLit by literalToken(" to ")
            val newlineLit by literalToken("\n")
            val digitRegex by regexToken("\\d+")

            /*
             * Intermediate parsers.
             */
            val digit by digitRegex map { it.text.toInt() }
            val move by skip(moveLit) and digit and skip(fromLit) and digit and skip(toLit) and digit map {
                Move(
                    it.t1,
                    it.t2,
                    it.t3
                )
            }
            val moves by separatedTerms(move, newlineLit)

            /*
             * Root parser.
             */
            override val rootParser by moves
        }

        return grammar.parseToEnd(input)
    }


    override fun runPart1(input: String): String {
        parse(input).forEach { move ->
            for (i in 1..move.num) {
                stacksById[move.toStack]!!.push(stacksById[move.fromStack]!!.pop())
            }
        }

        return (1..9).map { stacksById[it]!!.pop() }.joinToString(separator = "")
    }

    override fun runPart2(input: String): String {
        parse(input).forEach { move ->
            val containers = ArrayDeque<Char>()
            for (i in 1..move.num) {
                containers.addFirst(stacksById[move.fromStack]!!.pop())
            }

            while (containers.isNotEmpty()) {
                stacksById[move.toStack]!!.push(containers.removeFirst())
            }
        }

        return (1..9).map { stacksById[it]!!.pop() }.joinToString(separator = "")
    }

    // hack. this is from the default input
    private val stacksById: Map<Int, Stack> = mapOf(
        1 to Stack(listOf('G', 'J', 'Z')),
        2 to Stack(listOf('C', 'V', 'F', 'W', 'P', 'R', 'L', 'Q')),
        3 to Stack(listOf('R', 'G', 'L', 'C', 'M', 'P', 'F')),
        4 to Stack(listOf('M', 'H', 'P', 'W', 'B', 'F', 'L')),
        5 to Stack(listOf('Q', 'V', 'S', 'F', 'C', 'G')),
        6 to Stack(listOf('L', 'T', 'Q', 'M', 'Z', 'J', 'H', 'W')),
        7 to Stack(listOf('V', 'B', 'S', 'F', 'H')),
        8 to Stack(listOf('S', 'Z', 'J', 'F')),
        9 to Stack(listOf('T', 'B', 'H', 'F', 'P', 'D', 'C', 'M'))
    )

    // hack. this is just the moves part of the default input
    override val defaultInput = """move 1 from 5 to 6
move 5 from 6 to 7
move 10 from 7 to 3
move 4 from 8 to 4
move 2 from 5 to 4
move 4 from 3 to 6
move 6 from 2 to 4
move 8 from 6 to 9
move 5 from 9 to 2
move 7 from 2 to 7
move 2 from 1 to 4
move 3 from 3 to 8
move 1 from 5 to 9
move 1 from 3 to 8
move 1 from 1 to 2
move 11 from 4 to 6
move 2 from 5 to 6
move 10 from 9 to 1
move 4 from 8 to 3
move 7 from 7 to 1
move 9 from 1 to 2
move 1 from 6 to 5
move 1 from 5 to 9
move 5 from 3 to 8
move 2 from 9 to 1
move 5 from 3 to 9
move 3 from 6 to 8
move 5 from 9 to 6
move 6 from 6 to 3
move 3 from 3 to 2
move 1 from 9 to 8
move 13 from 2 to 3
move 3 from 8 to 1
move 11 from 1 to 4
move 3 from 4 to 1
move 2 from 6 to 5
move 4 from 6 to 8
move 17 from 3 to 9
move 1 from 1 to 8
move 1 from 6 to 5
move 1 from 3 to 7
move 1 from 7 to 4
move 3 from 4 to 1
move 1 from 3 to 8
move 4 from 8 to 1
move 3 from 5 to 9
move 1 from 6 to 4
move 4 from 4 to 8
move 2 from 8 to 4
move 2 from 1 to 6
move 4 from 8 to 6
move 1 from 8 to 3
move 6 from 6 to 3
move 6 from 3 to 9
move 6 from 1 to 4
move 5 from 8 to 4
move 1 from 3 to 6
move 3 from 1 to 7
move 1 from 6 to 7
move 4 from 4 to 5
move 24 from 9 to 5
move 2 from 9 to 1
move 27 from 5 to 7
move 13 from 7 to 2
move 1 from 5 to 9
move 7 from 2 to 7
move 1 from 9 to 8
move 5 from 2 to 8
move 1 from 2 to 5
move 1 from 5 to 7
move 21 from 4 to 1
move 1 from 4 to 6
move 1 from 6 to 5
move 22 from 7 to 5
move 2 from 7 to 8
move 7 from 5 to 4
move 1 from 4 to 5
move 2 from 7 to 9
move 5 from 5 to 2
move 5 from 4 to 2
move 3 from 5 to 1
move 7 from 8 to 7
move 1 from 4 to 1
move 23 from 1 to 8
move 2 from 9 to 4
move 11 from 8 to 3
move 3 from 1 to 3
move 1 from 4 to 2
move 12 from 3 to 2
move 7 from 7 to 3
move 3 from 2 to 1
move 1 from 4 to 9
move 1 from 1 to 3
move 9 from 8 to 6
move 2 from 5 to 4
move 3 from 1 to 7
move 3 from 2 to 4
move 7 from 2 to 3
move 9 from 3 to 4
move 7 from 5 to 2
move 2 from 7 to 2
move 1 from 7 to 2
move 13 from 4 to 6
move 1 from 9 to 8
move 2 from 8 to 2
move 12 from 2 to 1
move 3 from 3 to 1
move 1 from 8 to 1
move 5 from 3 to 7
move 3 from 2 to 8
move 7 from 2 to 5
move 3 from 8 to 3
move 1 from 4 to 8
move 22 from 6 to 4
move 1 from 3 to 6
move 3 from 5 to 8
move 4 from 5 to 8
move 1 from 3 to 9
move 8 from 4 to 2
move 8 from 8 to 3
move 1 from 6 to 3
move 4 from 2 to 6
move 1 from 9 to 4
move 5 from 3 to 9
move 2 from 8 to 1
move 3 from 2 to 1
move 10 from 4 to 8
move 4 from 7 to 6
move 10 from 1 to 3
move 9 from 8 to 2
move 1 from 7 to 1
move 15 from 3 to 1
move 1 from 8 to 9
move 4 from 4 to 1
move 17 from 1 to 3
move 3 from 2 to 3
move 3 from 6 to 8
move 5 from 9 to 7
move 11 from 1 to 8
move 4 from 7 to 8
move 6 from 2 to 5
move 2 from 1 to 4
move 4 from 6 to 8
move 16 from 8 to 6
move 2 from 6 to 1
move 1 from 9 to 5
move 1 from 7 to 5
move 2 from 5 to 6
move 5 from 6 to 3
move 2 from 8 to 5
move 1 from 2 to 1
move 10 from 6 to 3
move 6 from 5 to 9
move 2 from 1 to 2
move 2 from 4 to 2
move 1 from 2 to 4
move 5 from 9 to 2
move 1 from 4 to 3
move 1 from 9 to 7
move 1 from 6 to 1
move 1 from 1 to 7
move 2 from 7 to 5
move 7 from 2 to 5
move 6 from 5 to 1
move 1 from 2 to 3
move 1 from 4 to 1
move 2 from 8 to 9
move 8 from 1 to 3
move 2 from 5 to 3
move 29 from 3 to 9
move 5 from 3 to 8
move 6 from 8 to 5
move 1 from 6 to 5
move 6 from 3 to 2
move 2 from 2 to 4
move 1 from 1 to 7
move 18 from 9 to 6
move 2 from 2 to 9
move 2 from 2 to 8
move 13 from 6 to 8
move 1 from 7 to 4
move 3 from 5 to 6
move 1 from 5 to 7
move 1 from 7 to 4
move 14 from 9 to 3
move 3 from 4 to 5
move 1 from 9 to 7
move 14 from 3 to 2
move 1 from 7 to 3
move 4 from 2 to 5
move 16 from 8 to 6
move 11 from 6 to 9
move 13 from 6 to 4
move 5 from 5 to 2
move 12 from 2 to 4
move 19 from 4 to 3
move 7 from 4 to 5
move 14 from 5 to 2
move 2 from 3 to 6
move 3 from 9 to 5
move 2 from 6 to 2
move 1 from 5 to 2
move 3 from 5 to 4
move 3 from 4 to 1
move 7 from 9 to 6
move 4 from 6 to 1
move 1 from 1 to 8
move 3 from 6 to 9
move 1 from 8 to 7
move 1 from 9 to 6
move 4 from 1 to 2
move 1 from 7 to 2
move 2 from 9 to 8
move 10 from 2 to 9
move 2 from 2 to 9
move 11 from 3 to 7
move 1 from 8 to 9
move 2 from 3 to 7
move 1 from 1 to 7
move 10 from 2 to 4
move 3 from 4 to 1
move 4 from 1 to 8
move 1 from 6 to 5
move 6 from 7 to 9
move 3 from 9 to 1
move 1 from 5 to 1
move 4 from 4 to 2
move 5 from 2 to 1
move 1 from 2 to 7
move 2 from 7 to 6
move 1 from 2 to 1
move 2 from 9 to 1
move 3 from 4 to 7
move 1 from 3 to 7
move 2 from 8 to 3
move 2 from 6 to 5
move 2 from 5 to 8
move 10 from 7 to 2
move 6 from 9 to 1
move 1 from 7 to 3
move 2 from 8 to 9
move 7 from 3 to 7
move 7 from 3 to 9
move 1 from 8 to 9
move 6 from 2 to 8
move 13 from 9 to 1
move 6 from 9 to 8
move 2 from 2 to 7
move 3 from 7 to 1
move 1 from 8 to 1
move 1 from 1 to 6
move 16 from 1 to 4
move 2 from 7 to 5
move 12 from 4 to 9
move 4 from 8 to 6
move 2 from 5 to 1
move 8 from 8 to 4
move 2 from 4 to 5
move 1 from 8 to 6
move 4 from 6 to 8
move 19 from 1 to 9
move 3 from 8 to 5
move 1 from 6 to 9
move 2 from 2 to 1
move 10 from 4 to 9
move 1 from 1 to 2
move 2 from 1 to 5
move 4 from 7 to 9
move 1 from 8 to 2
move 1 from 2 to 6
move 7 from 5 to 4
move 11 from 9 to 8
move 1 from 4 to 3
move 10 from 8 to 1
move 1 from 2 to 3
move 29 from 9 to 3
move 2 from 6 to 5
move 1 from 5 to 3
move 5 from 9 to 3
move 1 from 8 to 9
move 1 from 9 to 3
move 6 from 4 to 6
move 1 from 5 to 1
move 1 from 6 to 3
move 2 from 1 to 5
move 1 from 9 to 5
move 37 from 3 to 2
move 3 from 6 to 2
move 1 from 6 to 2
move 1 from 6 to 4
move 3 from 1 to 3
move 2 from 1 to 6
move 35 from 2 to 1
move 1 from 6 to 8
move 5 from 1 to 8
move 7 from 1 to 6
move 5 from 3 to 7
move 1 from 8 to 7
move 3 from 7 to 5
move 4 from 2 to 9
move 1 from 2 to 1
move 1 from 4 to 3
move 3 from 7 to 1
move 1 from 3 to 6
move 1 from 1 to 9
move 5 from 9 to 2
move 18 from 1 to 3
move 6 from 1 to 8
move 6 from 3 to 7
move 4 from 8 to 6
move 4 from 6 to 7
move 9 from 7 to 8
move 3 from 2 to 7
move 4 from 6 to 1
move 3 from 5 to 3
move 3 from 2 to 5
move 3 from 6 to 1
move 4 from 7 to 4
move 6 from 5 to 9
move 3 from 1 to 9
move 1 from 6 to 1
move 15 from 8 to 2
move 1 from 8 to 5
move 3 from 4 to 8
move 1 from 5 to 1
move 1 from 6 to 5
move 11 from 3 to 9
move 12 from 2 to 3
move 3 from 8 to 1
move 15 from 1 to 2
move 8 from 9 to 4
move 8 from 4 to 9
move 4 from 2 to 5
move 1 from 4 to 6
move 1 from 2 to 8
move 1 from 6 to 7
move 4 from 3 to 1
move 1 from 8 to 5
move 5 from 3 to 9
move 14 from 9 to 2
move 1 from 7 to 4
move 4 from 1 to 3
move 1 from 4 to 7
move 8 from 3 to 7
move 8 from 7 to 5
move 1 from 7 to 9
move 3 from 3 to 2
move 7 from 9 to 8
move 1 from 9 to 5
move 2 from 8 to 5
move 7 from 5 to 4
move 4 from 9 to 2
move 6 from 4 to 3
move 18 from 2 to 5
move 1 from 4 to 7
move 15 from 5 to 4
move 1 from 4 to 6
move 2 from 2 to 7
move 3 from 8 to 5
move 1 from 7 to 3
move 8 from 2 to 6
move 4 from 2 to 3
move 1 from 7 to 5
move 3 from 4 to 6
move 5 from 6 to 9
move 8 from 5 to 6
move 2 from 4 to 3
move 7 from 4 to 2
move 2 from 8 to 5
move 7 from 5 to 6
move 3 from 5 to 8
move 1 from 8 to 9
move 13 from 3 to 8
move 2 from 2 to 7
move 9 from 8 to 9
move 6 from 8 to 5
move 5 from 5 to 2
move 2 from 7 to 8
move 9 from 2 to 5
move 1 from 7 to 5
move 1 from 5 to 7
move 21 from 6 to 2
move 1 from 7 to 8
move 3 from 8 to 9
move 1 from 4 to 2
move 23 from 2 to 7
move 8 from 9 to 8
move 20 from 7 to 4
move 3 from 7 to 2
move 1 from 2 to 7
move 1 from 6 to 7
move 3 from 5 to 4
move 8 from 5 to 9
move 2 from 7 to 1
move 1 from 8 to 7
move 4 from 2 to 4
move 2 from 8 to 7
move 2 from 8 to 2
move 1 from 7 to 6
move 3 from 9 to 7
move 2 from 2 to 7
move 5 from 7 to 1
move 8 from 9 to 6
move 15 from 4 to 3
move 4 from 4 to 7
move 6 from 1 to 4
move 11 from 3 to 4
move 8 from 6 to 1
move 24 from 4 to 7
move 6 from 1 to 8
move 27 from 7 to 3
move 2 from 7 to 8
move 5 from 8 to 3
move 4 from 8 to 4
move 1 from 8 to 6
move 1 from 6 to 9
move 1 from 6 to 5
move 2 from 4 to 2
move 1 from 8 to 1
move 1 from 5 to 2
move 4 from 1 to 6
move 1 from 7 to 5
move 1 from 5 to 8
move 1 from 8 to 7
move 1 from 7 to 8
move 1 from 8 to 1
move 1 from 2 to 3
move 2 from 4 to 8
move 7 from 9 to 6
move 2 from 8 to 1
move 3 from 3 to 8
move 3 from 1 to 8
move 2 from 2 to 3
move 1 from 4 to 1
move 1 from 1 to 8
move 5 from 8 to 3
move 8 from 6 to 2
move 1 from 9 to 4
move 2 from 4 to 8
move 2 from 8 to 3
move 2 from 6 to 2
move 33 from 3 to 2
move 2 from 8 to 7
move 1 from 6 to 1
move 1 from 1 to 7
move 2 from 3 to 8
move 2 from 8 to 4
move 1 from 4 to 8
move 2 from 7 to 2
move 2 from 3 to 7
move 12 from 2 to 1
move 1 from 8 to 4
move 1 from 4 to 8
move 1 from 4 to 3
move 1 from 8 to 2
move 3 from 7 to 2
move 37 from 2 to 7
move 1 from 1 to 7
move 12 from 7 to 1
move 13 from 1 to 7
move 1 from 3 to 4
move 35 from 7 to 6
move 1 from 4 to 5
move 3 from 7 to 4
move 1 from 5 to 7
move 2 from 3 to 4
move 23 from 6 to 9
move 3 from 1 to 5
move 3 from 3 to 7
move 1 from 3 to 6
move 2 from 5 to 3
move 23 from 9 to 8
move 2 from 4 to 9
move 16 from 8 to 2
move 2 from 7 to 3
move 1 from 5 to 8
move 3 from 7 to 6
move 1 from 9 to 8
move 3 from 8 to 1
move 1 from 9 to 1
move 11 from 6 to 5
move 2 from 4 to 1
move 4 from 8 to 6
move 16 from 2 to 3
move 9 from 1 to 9
move 1 from 8 to 4
move 3 from 9 to 3
move 1 from 1 to 4
move 1 from 9 to 4
move 7 from 5 to 2
move 6 from 2 to 5
move 1 from 8 to 6
move 22 from 3 to 7
move 8 from 5 to 8
move 4 from 4 to 9
move 2 from 1 to 8
move 16 from 7 to 2
move 1 from 3 to 5
move 14 from 2 to 7
move 2 from 2 to 4
move 6 from 9 to 3"""
}