// Originally generated by the template in CodeDAO
package kotlinadventofcode.`2022`

import kotlinadventofcode.Day

class `2022-10` : Day {

    override fun runPartOneNoUI(input: String): String {
        var result = 0
        var cycle = 1
        var x = 1
        input.lines().forEach {
            if (cycle in setOf(20, 60, 100, 140, 180, 220)) result += x * cycle

            if (it == "noop") cycle++
            else {
                cycle++
                if (cycle in setOf(20, 60, 100, 140, 180, 220)) result += x * cycle
                x += it.substring(5).toInt()
                cycle++
            }
        }

        return result.toString()
    }

    override fun runPartTwoNoUI(input: String): String {
        var cycle = 1
        var x = 1
        var result = ""
        var lineResult = ""
        input.lines().forEach {

            if (it == "noop") {
                if (lineResult.length >= x - 1 && lineResult.length <= x + 1) lineResult += '#'
                else lineResult += '.'
                cycle++
                if (lineResult.length == 40) {
                    result += lineResult + "\n"
                    lineResult = ""
                }
            }

            else {

                if (lineResult.length >= x - 1 && lineResult.length <= x + 1) lineResult += '#'
                else lineResult += '.'
                cycle++
                if (lineResult.length == 40) {
                    result += lineResult + "\n"
                    lineResult = ""
                }


                if (lineResult.length >= x - 1 && lineResult.length <= x + 1) lineResult += '#'
                else lineResult += '.'
                cycle++
                if (lineResult.length == 40) {
                    result += lineResult + "\n"
                    lineResult = ""
                }

                x += it.substring(5).toInt()

            }
        }

        return result
    }

    override val defaultInput = """noop
noop
noop
addx 5
addx 1
addx 4
addx 1
noop
addx 4
noop
addx 1
addx 4
addx 8
addx -7
addx 3
addx 1
noop
addx 4
addx 2
addx 5
addx -1
noop
addx -37
noop
noop
addx 3
addx 2
addx 13
addx 12
addx -15
addx -2
addx 2
addx -11
addx 18
addx 2
addx -15
addx 16
addx 5
addx 2
addx 5
noop
noop
noop
addx 3
addx -2
addx -38
noop
addx 3
addx 4
noop
noop
noop
noop
noop
addx 5
addx 5
noop
noop
addx 21
addx -17
addx 6
noop
noop
noop
noop
addx 5
noop
noop
noop
noop
noop
addx 3
addx 5
addx -38
noop
noop
addx 5
addx -2
addx 1
addx 7
noop
addx 22
addx -18
addx -11
addx 27
addx -13
addx 2
addx 5
addx -8
addx 9
addx 2
noop
addx 7
noop
addx 1
noop
addx -38
noop
addx 2
addx 5
addx -3
noop
addx 8
addx 11
addx -6
noop
addx 24
addx -31
addx 10
addx 2
addx 5
addx 3
noop
addx 2
addx -29
addx 21
addx 11
addx 5
addx -39
addx 4
addx -2
addx 2
addx 7
noop
addx -1
addx 2
noop
addx 4
noop
addx 1
addx 2
addx 5
addx 2
noop
noop
addx -6
addx 9
addx -18
addx 25
addx 3
noop
addx -17
noop"""
}