// Originally generated by the template in CodeDAO
package kotlinadventofcode.`2015`

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class `2015-02-Test` {
    @Test fun testDefaultPart1() {
        assertEquals("1588178", `2015-02`().runPart1())
    }

    // DO NOT DELETE. I'm yet another code generation helper comment.
}