// Originally generated by the template in CodeDAO
package kotlinadventofcode.`2015`

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlinadventofcode.`2015`.`2015-13`.*

class `2015-13-Test` {

    private infix fun String.when1runsWith(input: String) {
        assertEquals(this, `2015-13`().runPart1(input))
    }

    private infix fun String.when2runsWith(input: String) {
        assertEquals(this, `2015-13`().runPart2(input))
    }

    @Test fun testDefaultPart1() {
        assertEquals("709", `2015-13`().runPart1())
    }

    @Test fun testDefaultPart2() {
        assertEquals("668", `2015-13`().runPart2())
    }

    @Test
    fun testParse() {
        val input = """Alice would lose 81 happiness units by sitting next to Carol.
Alice would gain 42 happiness units by sitting next to David."""

        assertEquals(
            listOf(
                Effect(PersonId("Alice"), -81, PersonId("Carol")),
                Effect(PersonId("Alice"), 42, PersonId("David"))),
            `2015-13`().parse(input))
    }
}
