// Originally generated by the template in CodeDAO
package kotlinadventofcode.`2015`

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class `2015-08-Test` {
    @Test fun testDefaultPart1() {
        assertEquals("1350", `2015-08`().runPart1())
    }

    @Test fun testDefaultPart2() {
        assertEquals("2085", `2015-08`().runPart2())
    }
}
