// Originally generated by the template in CodeDAO
package kotlinadventofcode.`2015`

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class `2015-03-Test` {
    @Test fun testDefaultPart1() {
        assertEquals("2572", `2015-03`().runPart1())
    }

    @Test fun testDefaultPart2() {
        assertEquals("2631", `2015-03`().runPart2())
    }
}
