// Originally generated by the template in CodeDAO
package kotlinadventofcode.`2015`

import kotlin.test.Test
import kotlin.test.assertEquals

class `2015-04-Test` {
    @Test fun testDefaultPart1() {
        assertEquals("117946", `2015-04`().runPartOneNoUI())
    }

    @Test fun testDefaultPart2() {
        assertEquals("3938038", `2015-04`().runPartTwoNoUI())
    }
}
