// Originally generated by the template in CodeDAO
package kotlinadventofcode.`2015`

import kotlin.test.Test
import kotlin.test.assertEquals

class `2015-18-Test` {

    private infix fun String.when1runsWith(input: String) {
        assertEquals(this, `2015-18`().runPartOneNoUI(input))
    }

    private infix fun String.when2runsWith(input: String) {
        assertEquals(this, `2015-18`().runPartTwoNoUI(input))
    }

    @Test fun testDefaultPart1() {
        assertEquals("768", `2015-18`().runPartOneNoUI())
    }

    @Test fun testDefaultPart2() {
        assertEquals("781", `2015-18`().runPartTwoNoUI())
    }

}
