// Originally generated by the template in CodeDAO
package kotlinadventofcode.`2015`

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class `2015-11-Test` {

    private infix fun String.when1runsWith(input: String) {
        assertEquals(this, `2015-11`().runPart1(input))
    }

    private infix fun String.when2runsWith(input: String) {
        assertEquals(this, `2015-11`().runPart2(input))
    }

    @Test fun testEasy1() {
        "aabcc" when1runsWith "aaacc"
    }

    @Test fun testIcrement1() {
        assertEquals("aabcc", `2015-11`().increment("aabcb"))
    }

    @Test fun testDefaultPart1() {
        assertEquals("hepxxyzz", `2015-11`().runPart1())
    }

    @Test fun testDefaultPart2() {
        assertEquals("heqaabcc", `2015-11`().runPart2())
    }

}
