// Originally generated by the template in CodeDAO
package kotlinadventofcode.`2015`

import kotlin.test.Test
import kotlin.test.assertEquals

class `2015-21-Test` {

    private infix fun String.when1runsWith(input: String) {
        assertEquals(this, `2015-21`().runPartOneNoUI(input))
    }

    private infix fun String.when2runsWith(input: String) {
        assertEquals(this, `2015-21`().runPartTwoNoUI(input))
    }

    @Test fun testDefaultPart1() {
        assertEquals("78", `2015-21`().runPartOneNoUI())
    }

    @Test fun testDefaultPart2() {
        assertEquals("148", `2015-21`().runPartTwoNoUI())
    }

}
