// Originally generated by the template in CodeDAO
package kotlinadventofcode.`2015`

import kotlin.test.Test
import kotlin.test.assertEquals

class `2015-15-Test` {

    private infix fun String.when1runsWith(input: String) {
        assertEquals(this, `2015-15`().runPartOneNoUI(input))
    }

    private infix fun String.when2runsWith(input: String) {
        assertEquals(this, `2015-15`().runPartTwoNoUI(input))
    }

    @Test fun testDefaultPart1() {
        assertEquals("21367368", `2015-15`().runPartOneNoUI())
    }

    @Test fun testDefaultPart2() {
        assertEquals("1766400", `2015-15`().runPartTwoNoUI())
    }

}
