// Originally generated by the template in CodeDAO
package kotlinadventofcode.`2015`

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class `2015-05-Test` {
    @Test fun testDefaultPart1() {
        assertEquals("238", `2015-05`().runPart1())
    }

    @Test fun testDefaultPart2() {
        assertEquals("69", `2015-05`().runPart2())
    }
}
